// Generated by CoffeeScript 1.9.1
(function() {
  var app, express, server;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    return res.send('Hello World');
  });

  server = app.listen(8088, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('App listening at http://%s:%s', host, port);
  });

}).call(this);
